"""Fix ARRAY to JSON for SQLite compatibility

Revision ID: f6db1ea44272
Revises: 007_add_game_skills_table
Create Date: 2026-01-06 14:17:04.361619-05:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6db1ea44272'
down_revision = '007_add_game_skills_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert ARRAY to JSON with explicit casting for PostgreSQL
    op.execute('ALTER TABLE games ALTER COLUMN mechanics TYPE JSON USING array_to_json(mechanics)')
    
    op.alter_column('recommendations', 'feedback_boost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('recommendations', 'was_selected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('ix_recommendations_feedback_asesor', table_name='recommendations')
    op.drop_index('ix_recommendations_feedback_date', table_name='recommendations')
    op.drop_index('ix_recommendations_was_selected', table_name='recommendations')
    op.alter_column('scoring_configs', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index('ix_scoring_configs_is_active', table_name='scoring_configs')
    
    # Convert ARRAY to JSON with explicit casting for PostgreSQL
    op.execute('ALTER TABLE session_profiles ALTER COLUMN objectives TYPE JSON USING array_to_json(objectives)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert JSON back to ARRAY for PostgreSQL
    op.execute('ALTER TABLE games ALTER COLUMN mechanics TYPE VARCHAR[] USING ARRAY(SELECT json_array_elements_text(mechanics))')
    
    op.alter_column('recommendations', 'feedback_boost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('recommendations', 'was_selected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index('ix_recommendations_feedback_asesor', 'recommendations', ['feedback_asesor'], unique=False)
    op.create_index('ix_recommendations_feedback_date', 'recommendations', ['feedback_date'], unique=False)
    op.create_index('ix_recommendations_was_selected', 'recommendations', ['was_selected'], unique=False)
    op.alter_column('scoring_configs', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.create_index('ix_scoring_configs_is_active', 'scoring_configs', ['is_active'], unique=False)
    
    # Convert JSON back to ARRAY for PostgreSQL
    op.execute('ALTER TABLE session_profiles ALTER COLUMN objectives TYPE VARCHAR[] USING ARRAY(SELECT json_array_elements_text(objectives))')
    # ### end Alembic commands ###
